
cc_binary(
    name = "native",
    deps = ["//build_tools/jni:jni_linux64", "//project1/java:test_native_headers"],
    srcs = ["main.c"],
    visibility = ["//visibility:public"],
    linkshared = True
)
