package(default_visibility = ["//visibility:public"])

cc_library(
    name = "jni_athena",
    hdrs = ["include/jni.h", "platform/athena/jni_md.h"],
    includes = ["include", "platform/athena"],
)

cc_library(
    name = "jni_linux64",
    hdrs = ["include/jni.h", "platform/linux64/jni_md.h"],
    includes = ["include", "platform/linux64"],
)

cc_library(
    name = "jni_mac64",
    hdrs = ["include/jni.h", "platform/mac64/jni_md.h"],
    includes = ["include", "platform/mac64"],
)

cc_library(
    name = "jni_win32",
    hdrs = ["include/jni.h", "platform/win32/jni_md.h"],
    includes = ["include", "platform/win32"],
)
